#!/bin/bash


#------------------------------------------------------------------------------
foamVersion="OpenFOAM-v2112"


#------------------------------------------------------------------------------
cd ${0%/*} || exit 1
clear
source clean
source .color
source .preamble

#------------------------------------------------------------------------------

echo -e "   - Creating Paraview file\n\n"
touch results.foam


#------------------------------------------------------------------------------
if [ -f cad/backgroundMesh.unv ];
then
    echo "   - Background mesh exist, proceed..."
else
    echo "   - No background mesh exist, please create one'"
    echo ""
    exit
fi


#------------------------------------------------------------------------------
echo -e "\n
Start meshing
-------------------------------------------------------------------------------
"


#------------------------------------------------------------------------------
echo -e "   - Create background mesh"
ideasUnvToFoam cad/backgroundMesh.unv > logMeshing


#------------------------------------------------------------------------------
echo -e "   - Decompose the background mesh into 4 domains"
decomposePar >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Meshing with snappyHexMesh (~ 5 minutes)"
mpirun -np 4 snappyHexMesh -parallel -overwrite >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Reconstruct the mesh (optional)"
reconstructParMesh -constant >> logMeshing


#------------------------------------------------------------------------------
echo -e "   - Scale the mesh"
transformPoints -scale "(0.1 0.1 0.1)" >> logMeshing


#------------------------------------------------------------------------------
echo -e "\n
-------------------------------------------------------------------------------
End Meshing\n
"




echo -e "   - Creating Paraview file\n\n"
touch results.foam


#------------------------------------------------------------------------------
